name: Render library update
on:
  schedule:
  - cron: "00 12 * * 1-5"
    branches: main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c("flexdashboard", "plotly", "reshape2",
          "zoo", "xts", "dygraphs", "rio", "openxlsx", "parsedate",
          "janitor", "tidyverse", "readr", "forcats",
          "timetk", "scales", "viridis",
          "ISOweek", "fs"))
          rmarkdown::render("index.Rmd")
        shell: Rscript {0}
        
        
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin --force || echo "No changes to commit"
