name: Render library update
on:
  schedule:
  - cron: "0 9 * * 1-5"
    branches: main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run:
          Rscript -e "install.packages(c('tidyverse', 'janitor', 'zoo', 'httr', 'openxlsx'))"
      - name: Render r plot file
        run:
          Rscript -e "source('mobilityIE.R')"
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New Executive Order signed - data updated!' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
